GameId: "a912182b02d04191ba724c6e90cb84f3"
ClientVersion: "1.0.145-prod-s"
Name: "Corehaven Chronicles"
Description: "All contact has been lost with the imperial island outpost of Highrock. Merchants tell strange and disturbing tales of the dead rising, and worse! Set sail from the seaside hamlet of Corehaven, and discover what dark and foul mystery has befallen Highrock.\r\n\r\nJoin up with your friends to conquer the first chapter of Corehaven Chronicles: The Siege of Highrock. You\'ll need might, magic, tactics and a bit of luck in order to defeat all the bosses. Along the way you\'ll collect and upgrade epic gear, and challenge the progressively harder and harder difficulty levels: Normal, Hard, Nightmare and Infinite Difficulty."
MaxPlayers: 12
Tags: "Adventure"
Tags: "Fantasy"
Tags: "SocialHub"
Tags: "RPG"
Tags: "Multiplayer"
ScreenshotPaths: "C:\\Users\\eric\\Documents\\My Games\\Core\\Saved\\Maps\\Content_07-Boss_Fight\\Screenshots\\Corehaven_Thumb01.png"
ScreenshotPaths: "C:\\Users\\eric\\Documents\\My Games\\Core\\Saved\\Maps\\Content_07-Boss_Fight\\Screenshots\\Corehaven_011.png"
ScreenshotPaths: "C:\\Users\\eric\\Documents\\My Games\\Core\\Saved\\Maps\\Content_07-Boss_Fight\\Screenshots\\Corehaven_012.png"
ScreenshotPaths: "C:\\Users\\eric\\Documents\\My Games\\Core\\Saved\\Maps\\Content_07-Boss_Fight\\Screenshots\\Corehaven_018.png"
ReleaseNotes: "- Fixed a few script errors and incorrect visuals\r\n- Added some new epics, look for them in Nightmare and Infinite difficulty"
OwnerId: "37edf67a267b45bd8b93be513218b428"
